# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 20:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128)),
                ('allowed_orgs', models.ManyToManyField(to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=64)),
                ('data', models.TextField(max_length=256)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.GameParticipant')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(through='common.GameParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
