# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170922_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameparticipant',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
