# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_gameparticipant_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestat',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='common.GameParticipant'),
        ),
    ]
