# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('common', '0004_auto_20170923_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCodeGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('access_code', models.CharField(blank=True, editable=False, max_length=16, unique=True)),
            ],
            bases=('auth.group',),
        ),
    ]
