# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_accesscodegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='allowed_orgs',
            field=models.ManyToManyField(to='common.AccessCodeGroup'),
        ),
    ]
