# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20171023_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='common.WordList'),
        ),
    ]
